---
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: bgp-peers-receive-all
  namespace: openshift-frr-k8s
  labels:
    routeAdvertisements: receive-all
spec:
  bgp:
    bfdProfiles:
      - name: bfd-default
        detectMultiplier: {{ .Values.bgpDetectMultiplier }}
        receiveInterval: {{ .Values.bgpReceiveInterval }}
        transmitInterval: {{ .Values.bgpTransmitInterval }}
    routers:
      - asn: {{ .Values.bgpASN }}
        neighbors:
          {{- range $bgpNeighbor := .Values.bgpNeighbors }}
          - interface: {{ $bgpNeighbor.bgpBaseInterface }}.{{ $bgpNeighbor.bgpVLAN }}
            asn: {{ $bgpNeighbor.bgpASN }}
            bfdProfile: bfd-default
            disableMP: true
            dualStackAddressFamily: false
            holdTime: {{ $.Values.bgpNeighborHoldTime }}
            keepaliveTime: {{ $.Values.bgpNeighborKeepaliveTime }}
            enableGracefulRestart: {{ $.Values.bgpNeighborEnableGracefulRestart }}
            sourceaddress: {{ $bgpNeighbor.bgpSourceAddress }}
            toReceive:
              allowed:
                mode: all
          {{- end }}
