---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bgp-lla
spec:
  desiredState:
    interfaces:
      {{- range $bgpNeighbor := .Values.bgpNeighbors }}
      - name: {{ $bgpNeighbor.bgpBaseInterface }}.{{ $bgpNeighbor.bgpVLAN }}
        type: vlan
        state: up
        ipv4:
          enabled: false
          dhcp: false
        ipv6:
          enabled: true
          dhcp: false
        vlan:
          base-iface: {{ $bgpNeighbor.bgpBaseInterface }}
          id: {{ $bgpNeighbor.bgpVLAN }}
      {{- end }}