---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: tenant-7-public
spec:
  namespaceSelector:
    matchLabels:
      'tenant': 'tenant-7'
      'security-zone': 'public'
  network:
    topology: Layer2
    layer2:
      role: Primary
      subnets:
        - 10.7.20.0/24
