---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: tenant-8-public
spec:
  namespaceSelector:
    matchLabels:
      tenant: 'tenant-8'         # this label needs to match RouteAdvertisement
      security-zone: 'public'
  network:
    topology: Layer2
    layer2:
      ipam:
        lifecycle: Persistent
      role: Primary
      subnets:
        - 10.8.20.0/24
---
apiVersion: k8s.ovn.org/v1
kind: RouteAdvertisements
metadata:
  name: tenant-8-extranet
spec:
  advertisements:
    - PodNetwork
  frrConfigurationSelector:
    matchLabels:
      use-for-advertisements: 'true'   # this label needs to match FFRconfig label
  networkSelectors:
    - clusterUserDefinedNetworkSelector:
        networkSelector:
          matchLabels:
            tenant: 'tenant-8'      # this label needs to match cUDN label
      networkSelectionType: ClusterUserDefinedNetworks
  nodeSelector: {}
  targetVRF: auto
---
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  labels:
    use-for-advertisements: 'true'        # this label needs to match Route Advertisemnt
  name: receive-filtered-wk1
  namespace: openshift-frr-k8s
spec:
  bgp:
    bfdProfiles:
      - detectMultiplier: 4  # this should match the bfd settings on your router
        name: bfd-default
        receiveInterval: 200
        transmitInterval: 200
    routers:
      - asn: 65519         # this is the asn you are planning to use on OpenShift side
        neighbors:
          - address: x.x.x.x   #IP address of the BGP peer (aka your DC switch/router)
            asn: 65110             # ASN of your BGP peer
            bfdProfile: bfd-default
            disableMP: true
            dualStackAddressFamily: false
            holdTime: 9s
            keepaliveTime: 3s
            toReceive:
              allowed:
                mode: all
        vrf: extranet
  nodeSelector:                   # limit to only nodes that need to be peering up. 
    matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
          - worker1.example.com 
          - worker2.example.com 
