---
operatorGroups:
  - name: open-cluster-management
    createNamespace: true
    targetOwnNamespace: true
operators:
  - channel: release-2.14
    installPlanApproval: Manual
    automaticIntermediateManualUpgrades: true
    name: advanced-cluster-management
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    csv: advanced-cluster-management.v2.14.0
    namespace: open-cluster-management
